#!/usr/bin/env python3
"""
太音 · 古体字形 SVG path 提取脚本

从齊伋體（明刻本风格，SIL OFL）提取核心部首/指法符号的古体轮廓路径，
输出为 svg-paths.ts 的替换片段。

用法:
  python3 scripts/extract-ancient-paths.py

输出:
  1. apps/web/src/lib/svg-paths.qiji.ts  — 所有可替换 glyph 的 Qiji 版本
  2. console 打印替换建议
"""

import json
import os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

FONT_QIJI = "/tmp/qiji-combo.ttf"
OUTPUT_PATH = "apps/web/src/lib/svg-paths.qiji.ts"

# Unicode mappings for the Qiji font
# Right-hand shells — these are semi-enclosed in jianzipu; Qiji gives raw ancient forms
UNICODE_MAP = {
    # 右手指法外壳 (semi-enclosed)
    "rh_da": "丁",      # 打 → 丁形
    "rh_zhai": "倽",    # 摘 → 倽形 (啇)
    "rh_gou": "勹",     # 勾 → 勹
    "rh_mo": "木",      # 抹 → 木
    "rh_tiao": "乚",    # 挑 → 乚
    "rh_tuo": "乇",     # 托 → 乇
    "rh_pi": "尸",      # 劈/擘 → 尸
    # rh_ti "剔" is multi-stroke, skip

    # 左手指法（标准字符）
    "lh_da": "大",
    "lh_ming": "夕",    # 名/夕共用同一形态
    "lh_zhong": "中",

    # 顶部帽子
    "top_san": "艹",    # 散字头 (grass radical)

    # 弦序内核（标准字符）
    "str_1": "一", "str_2": "二", "str_3": "三", "str_4": "四",
    "str_5": "五", "str_6": "六", "str_7": "七",

    # 徽位（标准字符）
    "hui_1": "一", "hui_2": "二", "hui_3": "三",
    "hui_4": "四", "hui_5": "五", "hui_6": "六",
    "hui_7": "七", "hui_8": "八", "hui_9": "九",
    "hui_10": "十",
    # hui_11(十一), hui_12(十二), hui_13(十三) are ligatures — skip

    # 分位（标准字符）
    "fen_ban": "半",
    # fen_3(三分), fen_6(六分), fen_8(八分) are ligatures — skip
}


def extract_glyph(font, char):
    """Extract SVG path for a Unicode character from font."""
    cmap = font.getBestCmap()
    glyf = font['glyf']
    glyph_set = font.getGlyphSet()

    cp = ord(char)
    if cp not in cmap:
        return None, None, f"U+{cp:04X} not in cmap"
    gn = cmap[cp]
    if gn not in glyf:
        return None, None, f"glyph '{gn}' not in glyf"
    g = glyf[gn]
    pen = SVGPathPen(glyph_set)
    g.draw(pen, glyf)
    path = pen.getCommands()
    if not path:
        return None, None, "empty path"
    bbox = None
    if hasattr(g, 'xMin') and g.numberOfContours is not None:
        bbox = {
            "xMin": g.xMin, "yMin": g.yMin,
            "xMax": g.xMax, "yMax": g.yMax,
        }
    return path, bbox, None


def main():
    font_qiji = TTFont(FONT_QIJI)
    upem = font_qiji['head'].unitsPerEm
    print(f"齊伋體 unitsPerEm: {upem}")
    print()

    entries = {}
    for key, char in sorted(UNICODE_MAP.items()):
        path, bbox, err = extract_glyph(font_qiji, char)
        if path:
            entries[key] = {"d": path, "bbox": bbox}
            bbox_str = f"({bbox['xMin']},{bbox['yMin']},{bbox['xMax']},{bbox['yMax']})" if bbox else "N/A"
            print(f"  ✓ {key:12s} ← {char}  len={len(path):>4}  bbox={bbox_str}")
        else:
            print(f"  ✗ {key:12s} ← {char}  {err}")

    # Output TypeScript file
    lines = [
        "// ⚠ auto-generated by scripts/extract-ancient-paths.py",
        "// 來源：齊伋體（明代木刻版風格, SIL OFL 1.1）\n",
        "export interface GlyphEntry {",
        "  d: string;",
        "  bbox: { xMin: number; yMin: number; xMax: number; yMax: number; } | null;",
        "}\n",
        "export const ANCIENT_PATHS: Record<string, GlyphEntry> = {",
    ]
    for key, info in sorted(entries.items()):
        lines.append(f'  "{key}": {{ d: {json.dumps(info["d"])}, bbox: {json.dumps(info["bbox"])} }},')
    lines.append("};\n")
    lines.append(f"export const ANCIENT_UPEM = {upem};")

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")

    font_qiji.close()
    print(f"\n✓ 输出 {len(entries)} entries → {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
