#!/usr/bin/env python3
"""
太音 · SVG 积木路径提取脚本

从 TaiYinJianZiPuKaiTi.ttf 提取核心部首/指法符号的 SVG 轮廓路径，
输出为 TypeScript 字典文件 (svg-paths.ts)，供 SvgJianziBlock 使用。

输出结构：
  export interface GlyphEntry {
    d: string;          // SVG <path d="..." />
    bbox: { ... } | null;  // 包围盒（字体原生坐标，y 向上）
  }
  export const SVG_PATHS: Record<string, GlyphEntry> = { ... };
  export const FONT_UPEM = 1000;
"""

import json
import os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

FONT_PATH = "apps/web/public/fonts/TaiYinJianZiPuKaiTi.ttf"
OUTPUT_PATH = "apps/web/src/lib/svg-paths.ts"

TARGET_GLYPHS = {
    # 帽子层
    "top_san": "sm_san",
    "top_fan": "sm_fan",
    # 左手指法
    "lh_da": "sm_da",
    "lh_ming": "sm_ming",
    "lh_zhong": "sm_zhong",
    "lh_gui": "sm_gui",
    # 徽位
    "hui_1": "sm_1", "hui_2": "sm_2", "hui_3": "sm_3",
    "hui_4": "sm_4", "hui_5": "sm_5", "hui_6": "sm_6",
    "hui_7": "sm_7", "hui_8": "sm_8", "hui_9": "sm_9",
    "hui_10": "sm_10", "hui_11": "sm_11", "hui_12": "sm_12",
    "hui_13": "sm_13",
    # 分数
    "fen_ban": "sm_ban",
    "fen_3": "sm_3.ban",
    "fen_6": "sm_6.ban",
    "fen_8": "sm_8.ban",
    # 右手外壳 —— 半包围结构（弦序内核嵌入内部）
    "rh_gou": "lg_gou",
    "rh_tiao": "lg_tiao",
    "rh_tuo": "lg_tuo",
    "rh_da": "lg_da",
    "rh_pi": "lg_pi",
    "rh_zhai": "lg_zhai",
    "rh_ti": "lg_ti",
    "rh_mo": "lgw_mo",   # 抹（木）— 从复合连字 lgw_mo 提取
    # 弦序内核
    "str_1": "md_1", "str_2": "md_2", "str_3": "md_3",
    "str_4": "md_4", "str_5": "md_5", "str_6": "md_6",
    "str_7": "md_7",
}


def extract_glyph(font, glyph_name):
    glyf = font['glyf']
    glyph_set = font.getGlyphSet()
    if glyph_name not in glyf:
        return None, None
    g = glyf[glyph_name]
    pen = SVGPathPen(glyph_set)
    g.draw(pen, glyf)
    path = pen.getCommands()
    if not path:
        return None, None
    bbox = None
    if hasattr(g, 'xMin') and g.numberOfContours is not None:
        bbox = {
            "xMin": g.xMin, "yMin": g.yMin,
            "xMax": g.xMax, "yMax": g.yMax,
        }
    return path, bbox


def main():
    font = TTFont(FONT_PATH)
    upem = font['head'].unitsPerEm
    print(f"unitsPerEm: {upem}")

    entries = {}
    for key, glyph_name in sorted(TARGET_GLYPHS.items()):
        path, bbox = extract_glyph(font, glyph_name)
        if path:
            entries[key] = {"d": path, "bbox": bbox}
            print(f"  ✓ {key:15s} ← {glyph_name:12s}  {len(path):>4} chars")
        else:
            print(f"  ✗ {key:15s} ← {glyph_name:12s}  MISSING")

    lines = [
        "// ⚠ auto-generated by scripts/extract-svg-paths.py\n",
        "export interface GlyphEntry {",
        '  d: string;',
        "  bbox: { xMin: number; yMin: number; xMax: number; yMax: number; } | null;",
        "}\n",
        "export const SVG_PATHS: Record<string, GlyphEntry> = {",
    ]
    for key, info in sorted(entries.items()):
        lines.append(f'  "{key}": {{ d: {json.dumps(info["d"])}, bbox: {json.dumps(info["bbox"])} }},')
    lines.append("};\n")
    lines.append(f"export const FONT_UPEM = {upem};")

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\n✓ 输出 {len(entries)} entries → {OUTPUT_PATH}")
    font.close()


if __name__ == "__main__":
    main()
