#!/usr/bin/env python3
"""
太音 · 古体字形合并脚本

将齊伋體提取的古体 path 合并到 svg-paths.ts 中。
只替换标准 CJK 字符：左手指法、弦序、徽位、分位、散字头。
右手指法外壳（半包围结构）和复合连字保持当前不变。
"""

import json
import re

CURRENT_PATH = "apps/web/src/lib/svg-paths.ts"
ANCIENT_PATH = "apps/web/src/lib/svg-paths.qiji.ts"

# Keys to replace with Qiji ancient paths
REPLACE_KEYS = {
    "lh_da", "lh_ming", "lh_zhong",
    "top_san",
    "str_1", "str_2", "str_3", "str_4", "str_5", "str_6", "str_7",
    "hui_1", "hui_2", "hui_3", "hui_4", "hui_5",
    "hui_6", "hui_7", "hui_8", "hui_9", "hui_10",
    "fen_ban",
}


def load_paths(path, var_name="SVG_PATHS|ANCIENT_PATHS"):
    with open(path) as f:
        content = f.read()
    pattern = rf'export const (?:{var_name}).*?{{'
    match = re.search(pattern, content, re.DOTALL)
    if not match:
        return None
    brace = match.end() - 1
    end = content.rfind('};', brace)
    block = content[brace+1:end]

    entries = {}
    # Match each entry: "key": { ... }
    entry_re = re.compile(r'\s*"([^"]+)"\s*:\s*\{', re.DOTALL)
    d_re = re.compile(r'd:\s*"((?:[^"\\]|\\.)*)"')
    bbox_re = re.compile(r'"xMin":\s*(-?\d+).*?"yMin":\s*(-?\d+).*?"xMax":\s*(-?\d+).*?"yMax":\s*(-?\d+)')

    current_key = None
    for line in block.split('\n'):
        km = entry_re.match(line)
        if km:
            current_key = km.group(1)
            entries[current_key] = {"d": "", "bbox": None}
        dm = d_re.search(line)
        if dm and current_key:
            entries[current_key]["d"] = dm.group(1)
        if current_key and 'bbox' in line:
            if 'null' in line:
                entries[current_key]["bbox"] = None
            else:
                bm = bbox_re.search(line)
                if bm:
                    entries[current_key]["bbox"] = {
                        "xMin": int(bm.group(1)), "yMin": int(bm.group(2)),
                        "xMax": int(bm.group(3)), "yMax": int(bm.group(4)),
                    }
    return entries


def main():
    current = load_paths(CURRENT_PATH)
    ancient = load_paths(ANCIENT_PATH, "ANCIENT_PATHS")
    if not current or not ancient:
        print("✗ Failed to load path files")
        return

    print(f"当前: {len(current)} entries, 古体: {len(ancient)} entries")
    print(f"计划替换 {len(REPLACE_KEYS)} 个标准字符\n")

    replaced = 0
    for key in sorted(REPLACE_KEYS):
        if key not in current:
            print(f"  ✗ {key}: not in current")
            continue
        if key not in ancient:
            print(f"  ✗ {key}: not in ancient")
            continue
        old_len = len(current[key]["d"])
        new_len = len(ancient[key]["d"])
        current[key] = {
            "d": ancient[key]["d"],
            "bbox": ancient[key]["bbox"],
        }
        print(f"  ✓ {key:12s}  {old_len:>4} → {new_len:>4} chars")
        replaced += 1

    kept_count = len(current) - len(REPLACE_KEYS)
    print(f"\n保持当前字体路径: {kept_count} entries (右手指法外壳 + 复合连字)")

    lines = [
        "// ⚠ auto-generated by scripts/extract-svg-paths.py + merge-ancient-paths.py",
        "// 部分路径替换自：齊伋體（明代木刻版風格, SIL OFL 1.1）\n",
        "export interface GlyphEntry {",
        "  d: string;",
        "  bbox: { xMin: number; yMin: number; xMax: number; yMax: number; } | null;",
        "}\n",
        "export const SVG_PATHS: Record<string, GlyphEntry> = {",
    ]
    for key in sorted(current.keys()):
        info = current[key]
        bbox_json = json.dumps(info["bbox"]) if info["bbox"] else "null"
        lines.append(f'  "{key}": {{ d: {json.dumps(info["d"])}, bbox: {bbox_json} }},')
    lines.append("};\n")
    lines.append("export const FONT_UPEM = 1000;")

    with open("apps/web/src/lib/svg-paths.ts", "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\n✓ 替换 {replaced} 个古体路径 → apps/web/src/lib/svg-paths.ts")


if __name__ == "__main__":
    main()
